In [57]:
import requests
import pandas as pd

In [71]:
url = 'https://api.pushshift.io/reddit/search/submission'

In [111]:
params = {
    'size': 200,
    'subreddit': 'stonks'
}

In [112]:
res = requests.get(url,params)
res.status_code
data = res.json()
posts = data['data']

In [113]:
stonks = pd.DataFrame(posts)

'title' is header of post
'selftext' is body of post

In [114]:
stonks[['title','selftext','created_utc','subreddit']].sort_values(by='created_utc',ascending=False)

,title,selftext,created_utc,subreddit
0,I love this template,,1630398809,stonks
1,"With such a great brand name, terrific results...",,1630368914,stonks
2,"Root is about to run again, got my order parti...",,1630368734,stonks
3,Kemist,,1630330384,stonks
4,Smith &amp; Wesson announces earnings on Wedne...,,1630298564,stonks
...,...,...,...,...
95,"Stonks, Dank memes",,1628526251,stonks
96,This Guy Made A Crazy Good Investing Subreddit,,1628524507,stonks
97,Supersmash x,,1628518761,stonks
98,Any tips for a new investor anyone?,,1628476082,stonks
99,500 shares of each S&amp;P 500 stock vs $500 c...,[removed],1628462992,stonks

In [117]:
params = {
    'size': 100,
    'subreddit': 'stonks',
    'before': min(stonks['created_utc'])
}

In [118]:
res = requests.get(url,params)
res.status_code
data = res.json()
posts = data['data']

In [119]:
stonks1 = pd.DataFrame(posts)
stonks1[['title','selftext','created_utc','subreddit']].sort_values(by='created_utc',ascending=False)

,title,selftext,created_utc,subreddit
0,STONKS!,,1628457802,stonks
1,Hahahah,,1628410018,stonks
2,Stonks: RTX On,,1628409239,stonks
3,Stonks: RTX ON,,1628409115,stonks
4,Stonks&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;...,,1628396347,stonks
...,...,...,...,...
95,IPA overly short stonk?,2.5 times the whole float short yesterday alon...,1627066715,stonks
96,Selling my meager amount of AMC to pay for my ...,[removed],1627059278,stonks
97,Serious stonks,file:///var/mobile/Library/SMS/Attachments/af/...,1627057710,stonks
98,Friday,,1627043057,stonks
99,Explorashun,,1627037460,stonks

In [125]:
stonks_list = [stonks,stonks1]

In [127]:
pd.concat(stonks_list,ignore_index=True)

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_is_blocked,author_patreon_flair,...,crosspost_parent_list,media,media_embed,secure_media,secure_media_embed,is_gallery,gallery_data,author_cakeday,author_flair_background_color,author_flair_text_color
0,[],False,Appropriate_Quail_87,None,[],None,text,t2_e5o86jah,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,PutCallParody,None,[],None,text,t2_e76jz9jf,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,Puzzleheaded_Rub_136,None,[],None,text,t2_a1g468qm,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,Standard_Leg7223,None,[],None,text,t2_9n2apvpx,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,PutCallParody,None,[],None,text,t2_e76jz9jf,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,[],False,Ok-Conflict-6728,None,[],None,text,t2_2epsq6fq,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,[],False,Verumistruth,None,[],None,text,t2_k5drq,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,[],False,BOOMerang1230,None,[],None,text,t2_cieoydxp,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,[],False,welovebernie,None,[],None,text,t2_z2lrz,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,[],False,Undercoverdog___,None,[],None,text,t2_7jk7srz7,False,False,...,"[{'all_awardings': [], 'allow_live_comments': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN