Collect the following data 
1. equity (snp500 + world)
2. FI (T-bill+corpbonds index)
3. commodity (commodity index)
4. gold (london gold index)
5. long-vol (eurohedge log vol)   

1. '^SP500TR' (total return inc. div, oldest up to 1988) + 'IWDA.L' (oldest up to 2009)
2. 'IEF' (oldest up to 2002) + 'LQD' (up to 2002 !dividend distributed)
3. 'DJP' (up to 2006)
4. 'LBMA Gold Price' excel (1988) -  https://www.gold.org/goldhub/data/gold-prices
5. 'Euro hedge long-vol' excel (2005) - https://www.eurekahedge.com/Indices/IndexView/Eurekahedge/640/CBOE-Eurekahedge-Long-Volatility-Hedge-Fund-Index

### Date Range
2000-9-31
2021-9-31

In [16]:
import pandas_datareader.data as web
from pandas_datareader.yahoo.headers import DEFAULT_HEADERS
import datetime
import requests_cache

expire_after = datetime.timedelta(days=3)
session = requests_cache.CachedSession(cache_name='cache', backend='sqlite', expire_after=expire_after)
session.headers = DEFAULT_HEADERS

start = datetime.datetime(2021, 1, 4)

end = datetime.datetime(2021, 10, 1)
f = web.DataReader('IEF', 'yahoo', start, end, session=session)

In [17]:
f

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2021-01-04,120.059998,119.650002,119.680000,119.980003,5499000.0,119.272644
2021-01-05,119.889999,119.580002,119.870003,119.699997,5004400.0,118.994286
2021-01-06,119.120003,118.769997,119.120003,119.000000,10039300.0,118.298424
2021-01-07,118.660004,118.480003,118.580002,118.580002,7751700.0,117.880898
2021-01-08,118.430000,118.129997,118.349998,118.239998,8378700.0,117.542900
...,...,...,...,...,...,...
2021-09-27,115.599998,115.370003,115.400002,115.400002,6742100.0,115.319878
2021-09-28,115.220001,114.730003,114.980003,114.959999,10295500.0,114.880180
2021-09-29,115.360001,114.870003,115.199997,115.080002,8364000.0,115.000099
2021-09-30,115.260002,114.919998,114.970001,115.220001,7307900.0,115.139999
2021-10-01,115.660004,115.260002,115.360001,115.610001,19830100.0,115.610001